platform: darksky
name: "Weather forecast"
api_key: !secret dark_sky_key
update_interval:
  minutes: 10
monitored_conditions:
  - summary
  - hourly_summary
  - temperature
  - temperature_max
  - temperature_min