[snips-common]
bus = "mqtt"
mqtt = "mqtt:1883"
audio = ["satellite-development@mqtt"]
assistant = "/common-config/assistant"
user_dir = "/common-config/snips"

[snips-audio-server]
bind = "satellite-development@mqtt"

[snips-hotword]
model = "/usr/share/snips/hotword"
# hotword_id = "default"
# sensitivity = "0.5"
audio = ["satellite-development@mqtt"]

[snips-tts]
## Choose one tts provider (defaults to picotts)
provider = "marytts"
# provider = "picotts"
# provider = "makerstts"
# provider = "customtts"
## customtts specific configuration (here configured to use picotts)
# customtts = { command = ["pico2wave", "-w", "%%OUTPUT_FILE%%", "-l", "%%LANG%%", "%%TEXT%%"] }