[snips-common]
bus = "mqtt"
mqtt = "mqtt:1883"
audio = ["+@mqtt"]
assistant = "/common-config/assistant"
user_dir = "/common-config/snips"

[snips-analytics]

[snips-nlu]

[snips-asr]
audio = ["+@mqtt"]

[snips-dialogue]
session_timeout = 15
lambda_timeout = 5
retry_count = 1
sound-feedback-disabled-default= false
